mysite/urls.py
from django.contrib import admin
from django.urls import include, path

""" 
Optative paths forms:
path('pueblomagico/', include('pueblomagico.urls')),
path('pueblomagico/admin/', admin.site.urls),
"""

urlpatterns = [
    path('', include('pueblomagico.urls')),
    path('admin/', admin.site.urls)
]

pueblomagico/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name = 'pueblomagico'
urlpatterns = [
    #ej: /
    path('', views.index, name='index'),
    #ej: travel
    path('travel/', views.travel, name='travel'),
    #ej: travel/puebloid
    path('travel/<int:puebloid>/', views.choose, name='choose'),
    #ej: travel/puebloid/viajeid
    path('travel/<int:puebloid>/<int:viajeid>/', views.reserve, name='reserve'),
    #ej: ticket/ticketid
    path('ticket/<int:ticketid>', views.ticket, name='ticket'),
    #ej: post/
    path('post/', views.post, name='post'),
    #ej: post/id
    path('post/<int:id>/', views.town, name='town'),
    path('post/<int:id>/<int:comment>/', views.editComment, name='editComment'),
    path('users/signup/', views.signup, name='signup'),
    path('users/login/', views.login, name='login'),
    path('users/logout/', views.logout, name='logout')
]

pueblomagico/models/businessModel.py
from django.db import models
from django.utils import timezone as tz

# Create your models here.
class Estado(models.Model):
    nombre = models.CharField(max_length=200)
    def __str__(self):
        return "{}".format(self.nombre)

class Pueblo(models.Model):
    nombre = models.CharField(max_length=200)
    url = models.CharField(max_length=300)
    texto = models.TextField()
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.nombre)

class Camion(models.Model):
    modelo = models.CharField(max_length=200)
    placas = models.CharField(max_length=200)
    asientos = models.IntegerField(default=50)
    def __str__(self):
        return "{}".format(self.modelo)

class Hotel(models.Model):
    nombre = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    pueblo = models.ForeignKey(Pueblo, on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.nombre)

class Viaje(models.Model):
    fecha = models.DateTimeField()
    costo = models.DecimalField(max_digits=8,decimal_places=2)
    descripcion = models.CharField(max_length=300)
    camion = models.ForeignKey(Camion, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    pueblo = models.ForeignKey(Pueblo, on_delete=models.CASCADE)
    @property
    def localTime(self):
        return tz.localtime(self.fecha)
    def __str__(self):
        return "{} - {} - {}".format(self.camion,self.hotel, self.pueblo)

class Boleto(models.Model):
    fecha = models.DateTimeField()
    costo_total = models.DecimalField(max_digits=8,decimal_places=2)
    nombre = models.CharField(max_length=300)
    apellido = models.CharField(max_length=300)
    viaje = models.ForeignKey(Viaje, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    @property
    def localTime(self):
        return tz.localtime(self.fecha)
    def __str__(self):
        return "{} - {} - {}".format(self.nombre,self.apellido, self.viaje)

pueblomagico/models/postModel.py
from django.db import models
from django.contrib.auth.models import User
from .businessModel import Pueblo
from django.utils import timezone as tz

class Comentario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    publicacion = models.DateTimeField()
    modificacion = models.DateTimeField()
    pueblo = models.ForeignKey(Pueblo, on_delete=models.CASCADE)
    @property
    def localtimeLastUpdate(self):
        return tz.localtime(self.modificacion)
    def __str__(self):
        return "id:{},text:{}".format(self.id,self.texto)

pueblomagico/forms.py
from django import forms

class TravelForm(forms.Form):
    travel = forms.CharField(label='Ingrese el destino',max_length=100)

class CreateUserForm(forms.Form):
    user = forms.CharField(max_length=100)
    name = forms.CharField(max_length=100)
    lastname = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)
    password1 = forms.CharField(max_length=100)
    password2 = forms.CharField(max_length=100)
    currPage = forms.CharField(max_length=100)

class LoginUserForm(forms.Form):
    inputUser = forms.CharField(max_length=100)
    inputPassword = forms.CharField(max_length=100)
    currPage = forms.CharField(max_length=100)

class CreateCommentForm(forms.Form):
    user = forms.IntegerField()
    texto = forms.CharField()
    pueblo = forms.IntegerField()
    currPage = forms.CharField(max_length=100)

#Can be used for put and delete methods to edit or delete comments
#_method can handle PUT , DELETE and GET
class EditCommentForm(forms.Form):
    texto = forms.CharField()
    currPage = forms.CharField(max_length=100)
    _method = forms.CharField(max_length=6)

# handler will have the type of form to handle: reserve or payment 
class ReserveForm(forms.Form):
    name = forms.CharField(max_length=100)
    lastname = forms.CharField()
    seats = forms.IntegerField()
    email = forms.CharField(max_length=100)
    cost = forms.DecimalField()
    numerocuenta = forms.CharField(max_length=100)
    vencimiento = forms.DateField()
    cv = forms.IntegerField()

pueblomagico/views/businessView.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone as tz
from ..models import *
from ..forms import *

# Create your views here.

def index(request):
    ''' home page '''
    context = {'title': 'Inicio', 'page':"index"}
    return render(request, 'pueblomagico/index.html', context)

def travel(request):
    ''' It handles the search destination engine '''
    travels = Viaje.objects.all()
    towns_state = Pueblo.objects.all().select_related()
    target = (ts for ts in towns_state for tr in travels if ts.id==tr.pueblo_id)
    search = { (t.id,t.nombre,t.estado.nombre) for t in target }
    search =[{
        "id":s[0],
        "info": "{} | {}".format(s[1],s[2])
    } for s in search ]
    context = {
        'title': 'Viaja',
        'page':"travel",
        'search':search,
        'breadcrumbs': [{
            "title": "Destino",
            "url": "/travel/"
        }]
    }

    if request.method == 'POST':
        form = TravelForm(request.POST)
        if form.is_valid():
            #travel contains search info from the context used in the search bar engine
            travel = form.cleaned_data["travel"]
            id_travel = [t["id"] for t in search if t["info"]==travel][0]
            id_travel = str(int(id_travel))
            return HttpResponseRedirect(id_travel+"/")
        
        return render(request, 'pueblomagico/travel.html', context)
    else:
        return render(request, 'pueblomagico/travel.html', context)


def choose(request,puebloid:'i32'):
    ''' It shows reservation choices for the chosen town, id is the town's  '''
    if request.method == "GET":
        travel = Viaje.objects.all().filter(pueblo=puebloid).select_related()
        town = Pueblo.objects.select_related().get(pk=puebloid)
        context = {
            'title': 'Comprar', 
            'page':"travel",
            "town": town,
            "travel":travel, 
            'breadcrumbs': [{
                "title": "Destino",
                "url": "/travel/"
                },{
                "title": "Viaje",
                "url": f"/travel/{puebloid}"
            }]
        }
        return render(request, 'pueblomagico/choose.html', context)
    else:
        return redirect(puebloid)

def reserve(request,puebloid,viajeid):
    ''' handles the requests to make a reservation for the travel chosen '''
    travel = Viaje.objects.select_related().get(pk=viajeid)
    town = Pueblo.objects.select_related().get(pk=puebloid)
    context = {
        'title': 'Comprar', 
        'page':"travel",
        "town": town,
        "travel":travel, 
        'breadcrumbs': [{
            "title": "Destino",
            "url": "/travel/"
            },{
            "title": "Viaje",
            "url": f"/travel/{puebloid}"
            },{
            "title": "Reservación",
            "url": f"/travel/{puebloid}/{viajeid}"
        }]
    }
    if request.method == "POST":
        form = ReserveForm(request.POST)
        if form.is_valid():
            camion = Viaje.objects.select_related("camion").get(pk=viajeid).camion
            name = form.cleaned_data["name"]
            lastname = form.cleaned_data["lastname"]
            seats = form.cleaned_data["seats"]
            email = form.cleaned_data["email"]
            cost = form.cleaned_data["cost"]
            ticket = Boleto.objects.create(
                nombre = name,
                apellido = lastname,
                viaje = Viaje.objects.get(pk=viajeid),
                costo_total = cost,
                fecha = tz.now()
            )
            # to make sure there is enough seats to be bought by the client
            if camion.asientos >= seats:
                ticket.asientos = seats
                camion.asientos -= seats
                camion.save()
                ticket.cantidad = seats
                ticket.save()
                return redirect(f"/ticket/{ticket.id}")
        return redirect(f"/travel/{puebloid}/{viajeid}")
    else:
        return render(request, 'pueblomagico/reserve.html', context)

def ticket(request,ticketid):
    if request.method == "GET":
        ticket = Boleto.objects.select_related().get(pk=ticketid)
        context = {
            'title': 'Boleto', 
            'page':"travel",
            "ticket": ticket
        }
        return render(request, 'pueblomagico/ticket.html', context)
    else:
        return redirect("/travel/")

pueblomagico/views/postView.py
from django.shortcuts import render, redirect
from django.contrib import messages
from ..forms import *
from ..models import Pueblo, Estado, Comentario
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.utils import timezone as tz

def getCommentsbyID(pueblo: "i32") -> "Generator":
    """ Returns a Generator if there is any comment, None otherwise """
    if Comentario.objects.filter(pueblo=pueblo).count() > 0 : 
        return Comentario.objects.filter(pueblo=pueblo).order_by("-modificacion").select_related()
    else:
        None

def post(request):
    """ Page that shows the filter to choose the town so that to write or read comments """
    towns = Pueblo.objects.select_related().order_by('nombre')
    states = Estado.objects.all().order_by("nombre")
    context = {
        'title': 'Informate',
        'page': "post",
        'towns': towns,
        'states': states 
    }
    return render(request, 'pueblomagico/post.html', context)

def town(request,id:'i32'):
    """ It shows the comments written for a particular town or post
        for example, post/1 refers to all comments done to the town
        with ID 1 """
    context = {
        'title': 'Informate',
        'page': "post",
        'town': Pueblo.objects.all().select_related().get(pk=id) ,
        "comments" : getCommentsbyID(id)
    }

    if request.method == 'POST':
        form = CreateCommentForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data["user"]
            texto = form.cleaned_data["texto"].strip()
            pueblo_id = form.cleaned_data["pueblo"]
            page = form.cleaned_data["currPage"]
            comment = Comentario(
                user = User.objects.get(pk=user_id),
                texto = texto,
                publicacion = tz.now(),
                modificacion = tz.now(),
                pueblo = Pueblo.objects.get(pk=pueblo_id)
            )
            comment.save()
            #message that will display a success after the post request to create a comment
            messages.add_message(request, messages.SUCCESS,
                'Comentario creado correctamente',
                extra_tags='commentCreated'
            )
            return redirect(page)
        else:
            return redirect(page)
    else:
        return render(request, 'pueblomagico/town.html' , context)


def signup(request):
    """ create user """
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            name = form.cleaned_data["name"].lower()
            lastname = form.cleaned_data["lastname"].lower()
            email = form.cleaned_data["email"]
            password1 = form.cleaned_data["password1"]
            page = form.cleaned_data["currPage"]
            try:
                #If there is a user with that name an error must be displayed
                User.objects.get(username=user)
                messages.add_message(request, messages.ERROR,
                        f'Error de creación de usuario. {user} es un nombre que ya existe.  Intenta crear un nuevo nombre de usuario',
                    extra_tags='signupError'
                )
                return redirect(page)
            except User.DoesNotExist:
                u = User.objects.create_user(user,password = password1)
                u.first_name = name
                u.last_name = lastname
                u.email = email
                u.save()
                #message that will display a success after the post request to create a user
                messages.add_message(request, messages.SUCCESS,
                    'Usuario creado correctamente. Ya puedes iniciar sesión para comentar',
                     extra_tags='userCreated'
                )
                return redirect(page)
    return redirect("/")
    
def login(request):
    """login user """
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["inputUser"]
            password = form.cleaned_data["inputPassword"]
            page = form.cleaned_data["currPage"]
            user_auth = authenticate(username=user, password=password)
            if user_auth is not None:
                user = {
                    "userid" : user_auth.id,
                    "username": user_auth.username,
                    "firstname":user_auth.first_name,
                    "lastname" : user_auth.last_name,
                    "email" : user_auth.email
                }
                # user session has being created
                request.session["user"] = user
                messages.add_message(request, messages.SUCCESS,
                    f'Cuenta del usuario {user["username"]} iniciada correctamente',
                    extra_tags='loginSuccess'
                )
                return redirect(page)
            else:
                messages.add_message(request, messages.ERROR,
                    f'Error de acceso a cuenta de usuario. El usuario {user} no existe o se proporciono datos de acceso erróneos. Proporcione correctamente sus datos o cree una cuenta',
                    extra_tags='loginError'
                )
                return redirect(page)
    return redirect("/")

def logout(request):
    "logout user"
    if request.method == 'POST':
        if request.POST.get("logout") == "Ok":
            messages.add_message(request, messages.INFO,
                f'La sesión del  usuario {request.session["user"]["username"]} ha finalizado',
                extra_tags='logoutSuccess'
            )
            del request.session['user']
            return redirect(request.POST.get("currPage"))
    else:
        return redirect("/")

def editComment(request,id : "i32",comment : "i32"):
    """ id is the town's id and comment is the comment's id """
    if request.method == "POST":
        form = EditCommentForm(request.POST)
        if form.is_valid():
            page = form.cleaned_data["currPage"]
            method = form.cleaned_data["_method"]
            currComment = Comentario.objects.get(pk=comment)
            print(comment,page,method, currComment)
            if method == "GET":
                return render(request, 'pueblomagico/editComment.html', {
                    "comment" : currComment,
                    "town" : Pueblo.objects.get(pk=id)
                })
            elif method == "PUT":
                texto = form.cleaned_data["texto"].strip()
                Comentario.objects.filter(id=comment).update(texto=texto, modificacion=tz.now())
                #message that will display a success after the post request to edit a comment
                messages.add_message(request, messages.SUCCESS,
                    'Comentario editado correctamente',
                    extra_tags='commentEdited'
                )
                return redirect(f"/post/{id}")
            elif method == "DELETE": 
                currComment.delete()
                #message that will display a success after the post request to delete a comment
                messages.add_message(request, messages.SUCCESS,
                    'Comentario borrado correctamente',
                    extra_tags='commentDeleted'
                )
                return redirect(f"/post/{id}")
            else:
                return redirect(page)
        else:
            return redirect(f"/post/{id}")    
    else:
        return redirect(f"/post/{id}")

pueblomagico/templates/pueblomagico/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- title of tab page -->
    <title>
        {% block title_page %} Title tab page {% endblock  %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pueblomagico/bootstrap4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pueblomagico/css/base.css' %}">
    {% block custom_css %} {% endblock  %}
    <!-- fontawesome -->
    <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" 
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" 
        crossorigin="anonymous">
</head>
<body>

    {% if request.session.user %}
        <!-- navbar with user session information and options-->
        <div class="d-flex flex-row-reverse pt-2 pb-2 pb-lg-0 mb-0" id="navUserInSession">
            <div id="formLogoutUser">
                <form action="{% url 'pueblomagico:logout' %}" method="post"> 
                    {% csrf_token %}
                    <div class="form-row">
                        <input type="hidden" value="Ok" name="logout">
                        <input type="hidden" name="currPage" value="{{ request.get_full_path }}">
                    </div>
                    <button type="submit" class="btn btn-danger mr-4 pl-2"
                    id="btnLogout" value="Ok">
                        Cerrar sesión
                    </button>
                </form>
            </div>
            <div id="btnuserinfo">
                <button type="button" class="btn btn-info mr-4 pr-2 ml-3"
                data-toggle="popover" title="Usuario {{request.session.user.username}}" 
                data-html="true" data-placement="bottom"
                data-content="Nombre: {{request.session.user.firstname|upper}}<br>
                               Apellido: {{request.session.user.lastname|upper}}<br>
                               Email: {{request.session.user.email}}">
                    {{request.session.user.username}} <i class="fa fa-user" aria-hidden="true"></i>
                </button>
            </div>
        </div>
    {% endif %}
    <!-- Nav bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light pt-0">
        <!-- logo -->
        <a class="navbar-brand" href="{% url 'pueblomagico:index'%}">
            <img src="{% static 'pueblomagico/images/baggage.png' %}" alt="company logo"
            class="img-fluid" id="logo">
        </a>
        <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item" {% if page == 'index'%}id="currPage"{%endif%}>
                    <a class="nav-link" href="{% url 'pueblomagico:index'%}">
                        <i class="fa fa-home" aria-hidden="true"></i>Inicio</a>
                </li>
                <li class="nav-item" {% if page == 'travel'%}id="currPage"{%endif%}>
                    <a class="nav-link" href="{% url 'pueblomagico:travel'%}">
                        <i class="fa fa-plane" aria-hidden="true"></i>Reservaciones</a>
                </li>
                <li class="nav-item" {% if page == 'post'%}id="currPage"{%endif%}>
                    <a class="nav-link" href="{% url 'pueblomagico:post'%}">
                        <i class="fa fa-users"></i>Entérate</a>
                </li>
                <li class="nav-item ml-lg-6" id="navItemUserLogin">
                    <!-- Button trigger modal -->
                    <a class="btn btn-outline-primary"  data-toggle="modal" data-target="#userLoginModal"
                    id="linkUserLogin">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>Iniciar Sesión
                    </a> 
                </li>
                <li class="nav-item ml-lg-3 mt-2 mt-lg-0 ml-lg-6" id="navItemManagement">
                    <a class="btn btn-outline-info" href="/admin">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>Gerencia
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- modals -->
    {% include 'pueblomagico/user_login.html' %}
    {% include 'pueblomagico/create_user.html' %}

    <!-- individual title -->
    {% block title %}
        <div class="container">
            Titulo
        </div>
    {% endblock %}
    <!-- messages to the user -->
    <div class="container my-4">
        <span id="alertMessages">
        {% for message in messages %}
            {% if message.extra_tags == "loginError" %}
                <div class="alert alert-danger d-flex justify-content-between" role="alert">
                    <p >{{message}}</p>
                    <i class="fa fa-times" aria-hidden="true" style="cursor:pointer;"
                    id="closeUserAlert"></i>
                </div>
            {% elif message.extra_tags == "loginSuccess" %}
                <div class="alert alert-success d-flex justify-content-between" role="alert">
                    <p >{{message}}</p>
                    <i class="fa fa-times" aria-hidden="true" style="cursor:pointer;"
                    id="closeUserAlert"></i>
                </div>
            {% elif message.extra_tags == "signupError" %}
                <div class="alert alert-danger d-flex justify-content-between" role="alert">
                    <p >{{message}}</p>
                    <i class="fa fa-times" aria-hidden="true" style="cursor:pointer;"
                    id="closeUserAlert"></i>
                </div>
            {% elif message.extra_tags == "logoutSuccess" %}
                <div class="alert alert-info d-flex justify-content-between" role="alert">
                    <p >{{message}}</p>
                    <i class="fa fa-times" aria-hidden="true" style="cursor:pointer;"
                    id="closeUserAlert"></i>
                </div>
            {% elif message.extra_tags == "userCreated" %}
                <div class="alert alert-info d-flex justify-content-between" role="alert">
                    <p >{{message}}</p>
                    <i class="fa fa-times" aria-hidden="true" style="cursor:pointer;"
                    id="closeUserAlert"></i>
                </div>
            {% endif %}
        {% endfor %}
        </span>
    </div>
    
    <!-- individual content -->
    {% block content %}
        <div class="container">
            Cuerpo del contenido
        </div>   
    {% endblock %}


    <!-- footer -->
    <footer class="jumbotron jumbotron-fluid mb-0" id="footerbase">
        <div class="container">
            <div class="row">
                <div class="col-6 col-md-4">
                    <p class="lead font-weight-bolder footerTitle">Nuestros servicios</p>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a  href="{% url 'pueblomagico:index' %}#somos">Lo que hacemos</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'pueblomagico:travel'%}">Reserva con nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'pueblomagico:post' %}">Entérate y opina</a>
                        </li>
                    </ul>
                </div>              
                <div class="col-6 col-md-4">
                    <p class="lead font-weight-bolder footerTitle">Contactanos</p>
                    <ul>
                        <li><i class="fa fa-facebook mediaIcon" aria-hidden="true"></i></li>
                        <li><i class="fa fa-twitter mediaIcon" aria-hidden="true"></i></li>
                        <li><i class="fa fa-instagram mediaIcon" aria-hidden="true"></i></li>
                    </ul>                      
                </div>              
                <div class="col-12 col-md-4 mt-3 mt-md-0">
                    <p class="lead font-weight-bolder footerTitle">Ubicación</p>
                    <p>Avenida Azcapotzalco, CDMX, México</p>                     
                </div>              
                <div class="col-12 mt-3">
                    <p class="lead font-weight-bolder footerTitle">Mayores informes</p>
                    <p>Para mayores detalles acerca de los pueblos mágicos de México 
                        visita la <a href="https://www.gob.mx/sectur/articulos/pueblos-magicos-206528"
                        target="_blank">página oficial</a> de la Secretaría de Turismo.
                    </p>                     
                </div>              
            </div>
        </div>
    </footer>

    <!-- scripts -->
    <script src="{% static 'pueblomagico/bootstrap4/js/jquery.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
        crossorigin="anonymous">
    </script>
    <script src="{% static 'pueblomagico/bootstrap4/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'pueblomagico/js/userLoginValidation.js'%}"></script>
    <script src="{% static 'pueblomagico/js/createUserValidation.js'%}"></script>
    <script>
        /* popover for user information */
        $(function () {
            $('[data-toggle="popover"]').popover()
        });
        /* if there is a user connected there cannot be access to management acounts or
        to try to login as a new user until the current user session is over */
        let userloggedin = null;
        {% if request.session.user %}
            userloggedin = {{request.session.user|safe}};
        {% endif %}
        if(userloggedin) {
            $("#navItemUserLogin").prop("hidden","true");
            $("#navItemManagement").prop("hidden","true");
        } else {
            $("#navItemUserLogin").removeProp("hidden");
            $("#navItemManagement").removeProp("hidden");
        }
        /*removes message alerts to the user */
        $("#closeUserAlert").click( function(){
                    $(".container #alertMessages .alert").remove();
        });
    </script>
    {% block script_js %}{% endblock %}
</body>
</html>

pueblomagico/templates/pueblomagico/post.html
{% extends "pueblomagico/base.html" %}
{% load static %}

{% block title_page %} Entérate {% endblock  %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'pueblomagico/css/post.css' %}">
    <!-- it is going to be overriden by child town.css -->
    {% block post_css %} {% endblock  %}

{% endblock  %}

{% block title %}
<div class="jumbotron jumbotron-fluid" id="indexTitle">
    <div class="container">
        <div class="row">
            <div class="col-8 col-sm-6">
                <h1 class="display-4">Entérate y Opina</h1>
                <p >
                    Lee de las experiencias de otros y comenta las tuyas
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" id="breadTown" aria-current="page">
            <a href="{% url 'pueblomagico:post' %}">Pueblo</a>
        </li>
    </ol>
</nav>
<div class="container">
    <!-- content_travel will be overriden by its children: town.html, -->
    {% block content_post %}
        <p id="filtro">Filtrar por Estado</p>
        <select class="custom-select custom-select-lg mb-3">
            <option value="Todos">Todos</option>
            {% for state in states %}
                <option value="{{state}}">{{state}}</option>
            {% endfor %}
            
        </select>
        <div class="pb-4" id="listTowns">
            <ul>
                {% for town in towns %}
                    <li data-state="{{town.estado}}">
                        <a href="{% url 'pueblomagico:town' town.id %}" style="color: white;" >
                            {{ town.nombre }} | {{town.estado}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
            <a class="py-4" href="#filtro">Volver al inicio</a>
        </div>
        
    {% endblock %}

</div>
{% endblock %}


{% block script_js %}

    {% block post_script %}
    <script>
        function setBackGroundColor(num) {
            if (num%2 ==0) {
                return "#48CFAD";
            }
            return "#001f3f";
        }
        let towns = $("#listTowns li[data-state]");
        $("select").change( ()=>{
            towns.each( (i, town)=>{
                $(town).css({"display":"block", "background-color":setBackGroundColor(i+1)});
            });
            let select = $("select").val();
            select = select === "Todos" ? null : select;
            if(select ) {
                let y = 0;
                towns.each( (i, town)=>{
                    if ($( town ).data("state")!==select) {
                        $(town).css({"display":"none"});
                    } else {
                        $(town).css({"background-color":setBackGroundColor(y++)});
                    }   
                });
            }
        });
        
    </script>
    
    {% endblock %}

{% endblock %}